In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("salesdata.csv")
data

    Unnamed: 0     name region    sales  expenses
0            0  William    NaN  50000.0   42000.0
1            1     Emma  North  52000.0   43000.0
2            2    Sofia   East      NaN       NaN
3            3   Markus    NaN      NaN       NaN
4            4   Edward   West  42000.0   38000.0
5            5   Thomas   West  72000.0   39000.0
6            6    Ethan  South  49000.0   42000.0
7            7      NaN    NaN      NaN       NaN
8            8     Arun   West  67000.0   39000.0
9            9    Anika   East  65000.0   50000.0
10          10    Paulo  South  67000.0   45000.0

In [3]:
r=data.dropna()
r

    Unnamed: 0    name region    sales  expenses
1            1    Emma  North  52000.0   43000.0
4            4  Edward   West  42000.0   38000.0
5            5  Thomas   West  72000.0   39000.0
6            6   Ethan  South  49000.0   42000.0
8            8    Arun   West  67000.0   39000.0
9            9   Anika   East  65000.0   50000.0
10          10   Paulo  South  67000.0   45000.0

In [4]:
r1=data.dropna(how="all")
r1

    Unnamed: 0     name region    sales  expenses
0            0  William    NaN  50000.0   42000.0
1            1     Emma  North  52000.0   43000.0
2            2    Sofia   East      NaN       NaN
3            3   Markus    NaN      NaN       NaN
4            4   Edward   West  42000.0   38000.0
5            5   Thomas   West  72000.0   39000.0
6            6    Ethan  South  49000.0   42000.0
7            7      NaN    NaN      NaN       NaN
8            8     Arun   West  67000.0   39000.0
9            9    Anika   East  65000.0   50000.0
10          10    Paulo  South  67000.0   45000.0

In [5]:
r2=data.dropna(axis=1)
r2

    Unnamed: 0
0            0
1            1
2            2
3            3
4            4
5            5
6            6
7            7
8            8
9            9
10          10

In [6]:
data = {
    "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
    "B": [50, 40, 40, 30, 50],
    "C": [True, False, False, False, True]
}
df=pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [7]:
df=df.drop_duplicates().reset_index(drop=True)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamC  30  False

In [8]:
data=pd.read_csv("auto-mpg.csv")
data

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [9]:
print(data.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70
1  15.0          8         350.0        165    3693          11.5          70
2  18.0          8         318.0        150    3436          11.0          70
3  16.0          8         304.0        150    3433          12.0          70
4  17.0          8         302.0        140    3449          10.5          70

   origin                   car name
0       1  chevrolet chevelle malibu
1       1          buick skylark 320
2       1         plymouth satellite
3       1              amc rebel sst
4       1                ford torino

In [10]:
print(data.tail())

      mpg  cylinders  displacement horsepower  weight  acceleration  \
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin         car name
393          82       1  ford mustang gl
394          82       2        vw pickup
395          82       1    dodge rampage
396          82       1      ford ranger
397          82       1       chevy s-10

In [11]:
data=data.drop(columns=["mpg" ,"cylinders"])
data

,displacement,horsepower,weight,acceleration,model year,origin,car name
0,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,350.0,165,3693,11.5,70,1,buick skylark 320
2,318.0,150,3436,11.0,70,1,plymouth satellite
3,304.0,150,3433,12.0,70,1,amc rebel sst
4,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...
393,140.0,86,2790,15.6,82,1,ford mustang gl
394,97.0,52,2130,24.6,82,2,vw pickup
395,135.0,84,2295,11.6,82,1,dodge rampage
396,120.0,79,2625,18.6,82,1,ford ranger
397,119.0,82,2720,19.4,82,1,chevy s-10

In [12]:
print(data.head())

   displacement horsepower  weight  acceleration  model year  origin  \
0         307.0        130    3504          12.0          70       1
1         350.0        165    3693          11.5          70       1
2         318.0        150    3436          11.0          70       1
3         304.0        150    3433          12.0          70       1
4         302.0        140    3449          10.5          70       1

                    car name
0  chevrolet chevelle malibu
1          buick skylark 320
2         plymouth satellite
3              amc rebel sst
4                ford torino

# 62

In [13]:
df=pd.read_csv("ipl-matches.csv")
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [14]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 576.2 KB
None

In [15]:
print(df.head())

        ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2
2  1312198    Kolkata  2022-05-25   2022   Eliminator
3  1312197    Kolkata  2022-05-24   2022  Qualifier 1
4  1304116     Mumbai  2022-05-22   2022           70

                         Team1                 Team2  \
0             Rajasthan Royals        Gujarat Titans
1  Royal Challengers Bangalore      Rajasthan Royals
2  Royal Challengers Bangalore  Lucknow Super Giants
3             Rajasthan Royals        Gujarat Titans
4          Sunrisers Hyderabad          Punjab Kings

                              Venue            TossWinner TossDecision  \
0  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat
1  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field
2             Eden Gardens, Kolkata  Lucknow Super Giants        field
3             Eden Gardens, Kolkata        Gujarat Titans        field
4          Wankhede Stadium, Mumbai   Sunrisers Hyderabad          bat

  SuperOver                  WinningTeam    WonBy  Margin method  \
0         N               Gujarat Titans  Wickets     7.0    NaN
1         N             Rajasthan Royals  Wickets     7.0    NaN
2         N  Royal Challengers Bangalore     Runs    14.0    NaN
3         N               Gujarat Titans  Wickets     7.0    NaN
4         N                 Punjab Kings  Wickets     5.0    NaN

  Player_of_Match                                       Team1Players  \
0       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...

                                        Team2Players        Umpire1  \
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary

         Umpire2
0    Nitin Menon
1    Nitin Menon
2       MA Gough
3      VK Sharma
4  NA Patwardhan

In [16]:
sp=df[df["SuperOver"] == "Y"]
# print("SuperOver Matches:",sp)
print(sp[["ID","Team1","Team2","City","Date"]])

          ID                        Team1                        Team2  \
114  1254077               Delhi Capitals          Sunrisers Hyderabad
158  1216512        Kolkata Knight Riders          Sunrisers Hyderabad
159  1216517               Mumbai Indians              Kings XI Punjab
184  1216547  Royal Challengers Bangalore               Mumbai Indians
192  1216493               Delhi Capitals              Kings XI Punjab
203  1178426               Mumbai Indians          Sunrisers Hyderabad
244  1175365        Kolkata Knight Riders               Delhi Capitals
339  1082625                Gujarat Lions               Mumbai Indians
474   829741             Rajasthan Royals              Kings XI Punjab
533   729315        Kolkata Knight Riders             Rajasthan Royals
608   598017  Royal Challengers Bangalore             Delhi Daredevils
621   598004          Sunrisers Hyderabad  Royal Challengers Bangalore
819   419121          Chennai Super Kings              Kings XI Punjab
883   392190        Kolkata Knight Riders             Rajasthan Royals

          City        Date
114    Chennai  2021-04-25
158  Abu Dhabi  2020-10-18
159        NaN  2020-10-18
184        NaN  2020-09-28
192        NaN  2020-09-20
203     Mumbai  2019-05-02
244      Delhi  2019-03-30
339     Rajkot  2017-04-29
474  Ahmedabad  2015-04-21
533  Abu Dhabi  2014-04-29
608  Bangalore  2013-04-16
621  Hyderabad  2013-04-07
819    Chennai  2010-03-21
883  Cape Town  2009-04-23

In [17]:
print(df.head())

        ID       City        Date Season  MatchNumber  \
0  1312200  Ahmedabad  2022-05-29   2022        Final
1  1312199  Ahmedabad  2022-05-27   2022  Qualifier 2
2  1312198    Kolkata  2022-05-25   2022   Eliminator
3  1312197    Kolkata  2022-05-24   2022  Qualifier 1
4  1304116     Mumbai  2022-05-22   2022           70

                         Team1                 Team2  \
0             Rajasthan Royals        Gujarat Titans
1  Royal Challengers Bangalore      Rajasthan Royals
2  Royal Challengers Bangalore  Lucknow Super Giants
3             Rajasthan Royals        Gujarat Titans
4          Sunrisers Hyderabad          Punjab Kings

                              Venue            TossWinner TossDecision  \
0  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals          bat
1  Narendra Modi Stadium, Ahmedabad      Rajasthan Royals        field
2             Eden Gardens, Kolkata  Lucknow Super Giants        field
3             Eden Gardens, Kolkata        Gujarat Titans        field
4          Wankhede Stadium, Mumbai   Sunrisers Hyderabad          bat

  SuperOver                  WinningTeam    WonBy  Margin method  \
0         N               Gujarat Titans  Wickets     7.0    NaN
1         N             Rajasthan Royals  Wickets     7.0    NaN
2         N  Royal Challengers Bangalore     Runs    14.0    NaN
3         N               Gujarat Titans  Wickets     7.0    NaN
4         N                 Punjab Kings  Wickets     5.0    NaN

  Player_of_Match                                       Team1Players  \
0       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...

                                        Team2Players        Umpire1  \
0  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary

         Umpire2
0    Nitin Menon
1    Nitin Menon
2       MA Gough
3      VK Sharma
4  NA Patwardhan

In [18]:
c_w=df[(df["WinningTeam"]=="Chennai Super Kings") & (df["City"]=="Kolkata")]
print("Toatal:",c_w.shape[0])

Toatal: 5

In [19]:
ms=df[(df["Player_of_Match"]=="Ms Dhoni") & ((df["Team1"]=="Mumbai Indians")|(df["Team2"]=="Mumbai Indians"))]
ms

Empty DataFrame
Columns: [ID, City, Date, Season, MatchNumber, Team1, Team2, Venue, TossWinner, TossDecision, SuperOver, WinningTeam, WonBy, Margin, method, Player_of_Match, Team1Players, Team2Players, Umpire1, Umpire2]
Index: []

In [20]:
gt=df[(df["TossWinner"]=="Gujarat Titans") & (df["TossDecision"]=="bat") &
    (df["WinningTeam"]=="Gujarat Titans")]
gt

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
17,1304103,Pune,2022-05-10,2022,57,Gujarat Titans,Lucknow Super Giants,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,bat,N,Gujarat Titans,Runs,62.0,NaN,Shubman Gill,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['Q de Kock', 'KL Rahul', 'DJ Hooda', 'KS Shar...",KN Ananthapadmanabhan,MA Gough
39,1304081,Navi Mumbai,2022-04-23,2022,35,Gujarat Titans,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Gujarat Titans,bat,N,Gujarat Titans,Runs,8.0,NaN,Rashid Khan,"['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...","['SW Billings', 'SP Narine', 'SS Iyer', 'N Ran...",KN Ananthapadmanabhan,UV Gandhe

In [21]:
gt1=df[df["WinningTeam"]=="Gujarat Titans"]
gt1

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
12,1304108,Mumbai,2022-05-15,2022,62,Chennai Super Kings,Gujarat Titans,"Wankhede Stadium, Mumbai",Chennai Super Kings,bat,N,Gujarat Titans,Wickets,7.0,NaN,WP Saha,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",R Pandit,VK Sharma
17,1304103,Pune,2022-05-10,2022,57,Gujarat Titans,Lucknow Super Giants,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,bat,N,Gujarat Titans,Runs,62.0,NaN,Shubman Gill,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['Q de Kock', 'KL Rahul', 'DJ Hooda', 'KS Shar...",KN Ananthapadmanabhan,MA Gough
31,1304089,Mumbai,2022-04-30,2022,43,Royal Challengers Bangalore,Gujarat Titans,"Brabourne Stadium, Mumbai",Royal Challengers Bangalore,bat,N,Gujarat Titans,Wickets,6.0,NaN,R Tewatia,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['WP Saha', 'Shubman Gill', 'B Sai Sudharsan',...",HAS Khalid,VK Sharma
34,1304086,Mumbai,2022-04-27,2022,40,Sunrisers Hyderabad,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Umran Malik,"['Abhishek Sharma', 'KS Williamson', 'RA Tripa...","['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...",CB Gaffaney,Navdeep Singh
39,1304081,Navi Mumbai,2022-04-23,2022,35,Gujarat Titans,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Gujarat Titans,bat,N,Gujarat Titans,Runs,8.0,NaN,Rashid Khan,"['WP Saha', 'Shubman Gill', 'HH Pandya', 'DA M...","['SW Billings', 'SP Narine', 'SS Iyer', 'N Ran...",KN Ananthapadmanabhan,UV Gandhe
45,1304075,Pune,2022-04-17,2022,29,Chennai Super Kings,Gujarat Titans,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,field,N,Gujarat Titans,Wickets,3.0,NaN,DA Miller,"['RD Gaikwad', 'RV Uthappa', 'MM Ali', 'AT Ray...","['WP Saha', 'Shubman Gill', 'V Shankar', 'A Ma...",KN Ananthapadmanabhan,UV Gandhe
50,1304070,Mumbai,2022-04-14,2022,24,Gujarat Titans,Rajasthan Royals,"Dr DY Patil Sports Academy, Mumbai",Rajasthan Royals,field,N,Gujarat Titans,Runs,37.0,NaN,HH Pandya,"['MS Wade', 'Shubman Gill', 'V Shankar', 'HH P...","['JC Buttler', 'D Padikkal', 'R Ashwin', 'SV S...",CB Gaffaney,R Pandit
58,1304062,Mumbai,2022-04-08,2022,16,Punjab Kings,Gujarat Titans,"Brabourne Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,6.0,NaN,Shubman Gill,"['MA Agarwal', 'S Dhawan', 'JM Bairstow', 'LS ...","['MS Wade', 'Shubman Gill', 'B Sai Sudharsan',...",AK Chaudhary,VK Sharma
64,1304056,Pune,2022-04-02,2022,10,Gujarat Titans,Delhi Capitals,"Maharashtra Cricket Association Stadium, Pune",Delhi Capitals,field,N,Gujarat Titans,Runs,14.0,NaN,LH Ferguson,"['MS Wade', 'Shubman Gill', 'V Shankar', 'HH P...","['PP Shaw', 'TL Seifert', 'Mandeep Singh', 'RR...",KN Ananthapadmanabhan,UV Gandhe
70,1304050,Mumbai,2022-03-28,2022,4,Lucknow Super Giants,Gujarat Titans,"Wankhede Stadium, Mumbai",Gujarat Titans,field,N,Gujarat Titans,Wickets,5.0,NaN,Mohammed Shami,"['KL Rahul', 'Q de Kock', 'E Lewis', 'MK Pande...","['Shubman Gill', 'MS Wade', 'V Shankar', 'HH P...",PG Pathak,VK Sharma

In [22]:
import pandas as pd

# 63

In [23]:
df=pd.read_csv("spotify.csv")
df

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  str
 2   artists           113999 non-null  str
 3   album_name        113999 non-null  str
 4   track_name        113999 non-null  str
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(6), str(5)
memory usage: 26.8 MB

In [25]:
df.describe()

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [26]:
df.corr(numeric_only=True)

,Unnamed: 0,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
Unnamed: 0,1.000000,0.032142,-0.032743,-0.054736,0.003444,-0.055994,-0.005520,-0.027307,0.005107,-0.084952,0.076840,-0.070286,0.033639,0.053111,-0.025824,-0.021115
popularity,0.032142,1.000000,-0.007101,0.044082,0.035448,0.001056,-0.003853,0.050423,-0.013931,-0.044927,-0.025472,-0.095139,-0.005387,-0.040534,0.013205,0.031073
duration_ms,-0.032743,-0.007101,1.000000,-0.065263,-0.073426,0.058523,0.008114,-0.003470,-0.035556,-0.062600,-0.103788,0.124371,0.010321,-0.154479,0.024346,0.018225
explicit,-0.054736,0.044082,-0.065263,1.000000,0.122507,0.096955,0.004484,0.108588,-0.037212,0.307952,-0.094403,-0.103404,0.032549,-0.003381,-0.002816,0.038386
danceability,0.003444,0.035448,-0.073426,0.122507,1.000000,0.134325,0.036469,0.259077,-0.069219,0.108626,-0.171533,-0.185606,-0.131617,0.477341,-0.050450,0.207218
energy,-0.055994,0.001056,0.058523,0.096955,0.134325,1.000000,0.048006,0.761690,-0.078362,0.142509,-0.733906,-0.181879,0.184796,0.258934,0.247851,0.187126
key,-0.005520,-0.003853,0.008114,0.004484,0.036469,0.048006,1.000000,0.038590,-0.135916,0.020418,-0.040937,-0.006823,-0.001600,0.034103,0.010917,0.015065
loudness,-0.027307,0.050423,-0.003470,0.108588,0.259077,0.761690,0.038590,1.000000,-0.041764,0.060826,-0.589803,-0.433477,0.076899,0.279848,0.212446,0.191992
mode,0.005107,-0.013931,-0.035556,-0.037212,-0.069219,-0.078362,-0.135916,-0.041764,1.000000,-0.046532,0.095553,-0.049955,0.014012,0.021953,0.000566,-0.024092
speechiness,-0.084952,-0.044927,-0.062600,0.307952,0.108626,0.142509,0.020418,0.060826,-0.046532,1.000000,-0.002186,-0.089616,0.205219,0.036635,0.017273,-0.000011
acousticness,0.076840,-0.025472,-0.103788,-0.094403,-0.171533,-0.733906,-0.040937,-0.589803,0.095553,-0.002186,1.000000,0.104027,-0.020700,-0.107070,-0.208224,-0.176138
instrumentalness,-0.070286,-0.095139,0.124371,-0.103404,-0.185606,-0.181879,-0.006823,-0.433477,-0.049955,-0.089616,0.104027,1.000000,-0.079893,-0.324312,-0.050330,-0.082580
liveness,0.033639,-0.005387,0.010321,0.032549,-0.131617,0.184796,-0.001600,0.076899,0.014012,0.205219,-0.020700,-0.079893,1.000000,0.019086,0.000600,-0.023651
valence,0.053111,-0.040534,-0.154479,-0.003381,0.477341,0.258934,0.034103,0.279848,0.021953,0.036635,-0.107070,-0.324312,0.019086,1.000000,0.078273,0.133686
tempo,-0.025824,0.013205,0.024346,-0.002816,-0.050450,0.247851,0.010917,0.212446,0.000566,0.017273,-0.208224,-0.050330,0.000600,0.078273,1.000000,0.066641
time_signature,-0.021115,0.031073,0.018225,0.038386,0.207218,0.187126,0.015065,0.191992,-0.024092,-0.000011,-0.176138,-0.082580,-0.023651,0.133686,0.066641,1.000000

In [27]:
df.head()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [28]:
print(df.iloc[-5:, -5:])

        liveness  valence    tempo  time_signature  track_genre
113995    0.0863   0.0339  125.995               5  world-music
113996    0.1050   0.0350   85.239               4  world-music
113997    0.0839   0.7430  132.378               4  world-music
113998    0.2700   0.4130  135.960               4  world-music
113999    0.0893   0.7080   79.198               4  world-music

In [29]:
print(df.iloc[:5, :5])

   Unnamed: 0                track_id                 artists  \
0           0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino
1           1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward
2           2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN
3           3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis
4           4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet

                                          album_name  \
0                                             Comedy
1                                   Ghost (Acoustic)
2                                     To Begin Again
3  Crazy Rich Asians (Original Motion Picture Sou...
4                                            Hold On

                   track_name
0                      Comedy
1            Ghost - Acoustic
2              To Begin Again
3  Can't Help Falling In Love
4                     Hold On

In [30]:
df.tail()

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,...,-16.393,1,0.0422,0.640,0.928,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,...,-18.318,0,0.0401,0.994,0.976,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,...,-10.895,0,0.0420,0.867,0.000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,...,-10.889,1,0.0297,0.381,0.000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,...,-10.204,0,0.0725,0.681,0.000,0.0893,0.7080,79.198,4,world-music

In [31]:
df.isna().sum()

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [32]:
df.shape

(114000, 21)

In [33]:
df.drop(df.columns[0:3],axis=1,inplace=True)
df.shape

(114000, 18)

In [34]:
df.drop(df.index[0:10],axis=0,inplace=True)
df.shape

(113990, 18)

In [35]:
Q1=df['popularity'].quantile(0.25)
Q2=df['popularity'].quantile(0.75)
IQR=Q2-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q2+1.5*IQR
outliers=df[(df['popularity']<lower_bound)|(df['popularity']>upper_bound)]
print(outliers)

                      album_name                 track_name  popularity  \
20001  Unholy (feat. Kim Petras)  Unholy (feat. Kim Petras)         100
81051  Unholy (feat. Kim Petras)  Unholy (feat. Kim Petras)         100

       duration_ms  explicit  danceability  energy  key  loudness  mode  \
20001       156943     False         0.714   0.472    2    -7.375     1
81051       156943     False         0.714   0.472    2    -7.375     1

       speechiness  acousticness  instrumentalness  liveness  valence  \
20001       0.0864         0.013          0.000005     0.266    0.238
81051       0.0864         0.013          0.000005     0.266    0.238

         tempo  time_signature track_genre
20001  131.121               4       dance
81051  131.121               4         pop

In [36]:
df.shape

(113990, 18)

In [37]:
Q1=df['popularity'].quantile(0.25)
Q2=df['popularity'].quantile(0.75)
IQR=Q2-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q2+1.5*IQR
outliers=df[(df['popularity']<lower_bound)|(df['popularity']>upper_bound)]
df=df[~((df['popularity']<lower_bound)|(df['popularity']>upper_bound))]

In [38]:
df.shape

(113988, 18)

In [39]:
pd.crosstab(df.time_signature,df.track_genre)

track_genre,acoustic,afrobeat,alt-rock,alternative,ambient,anime,black-metal,bluegrass,blues,brazil,...,spanish,study,swedish,synth-pop,tango,techno,trance,trip-hop,turkish,world-music
time_signature,,,,,,,,,,,,,,,,,,,,,
0,0,0,1,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,3
1,9,5,1,2,39,7,20,5,6,5,...,2,6,6,2,17,3,5,7,3,7
3,99,52,56,64,264,63,129,80,97,42,...,55,49,49,16,167,26,37,38,75,132
4,869,930,940,922,648,923,838,909,894,939,...,937,934,928,981,784,969,949,951,909,844
5,13,13,2,12,46,7,13,6,3,14,...,6,11,17,1,32,2,9,4,12,14

# 64

In [40]:
df=pd.read_csv("car data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    str
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    str
 6   Seller_Type    301 non-null    str
 7   Transmission   301 non-null    str
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), str(4)
memory usage: 30.0 KB

In [42]:
r=df[(df["Car_Name"]=="ritz") & (df["Kms_Driven"]>30000)]
r1=r.shape[0]
r1

3

In [43]:
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [44]:
p=df[(df['Fuel_Type']=='Petrol') & (df['Selling_Price']>10) & (df['Year']==2017)]
p1=p.shape[0]
p1

2

In [45]:
s=df[(df["Car_Name"]=="swift") & (df["Selling_Price"]<4)]
s1=s.shape[0]
s1

1

In [46]:
a=df[(df['Fuel_Type']=='Petrol') & (df['Selling_Price']>10) & (df['Year']==2015) & 
    (df['Transmission']=='Automatic')]
a1=a.shape[0]
a1

1

In [49]:
t=df[(df['Selling_Price']<1) & 
    (df['Transmission']=='Automatic')] 
t

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
155,Honda Activa 4G,2017,0.48,0.51,4300,Petrol,Individual,Automatic,0
159,Honda Activa 4G,2017,0.45,0.51,4000,Petrol,Individual,Automatic,0
165,Activa 3g,2016,0.45,0.54,500,Petrol,Individual,Automatic,0
173,Activa 4g,2017,0.40,0.51,1300,Petrol,Individual,Automatic,0
177,Honda Activa 125,2016,0.35,0.57,24000,Petrol,Individual,Automatic,0
178,TVS Jupyter,2014,0.35,0.52,19000,Petrol,Individual,Automatic,0
185,Suzuki Access 125,2008,0.25,0.58,1900,Petrol,Individual,Automatic,0
186,TVS Wego,2010,0.25,0.52,22000,Petrol,Individual,Automatic,0
196,Activa 3g,2008,0.17,0.52,500000,Petrol,Individual,Automatic,0

In [50]:
b=df[(df['Fuel_Type']=='Petrol') & (df['Kms_Driven']>50000) & (df['Year']>=2010) & (df['Year']<=2015)]
b1=b.shape[0]
b1

23

In [51]:
c=df[(df['Present_Price']-df['Selling_Price'])>15]
# c1=c.shape[0]
c

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
50,fortuner,2012,14.90,30.61,104707,Diesel,Dealer,Automatic,0
59,fortuner,2014,19.99,35.96,41000,Diesel,Dealer,Automatic,0
62,fortuner,2014,18.75,35.96,78000,Diesel,Dealer,Automatic,0
78,corolla altis,2010,5.25,22.83,80000,Petrol,Dealer,Automatic,0
79,fortuner,2012,14.50,30.61,89000,Diesel,Dealer,Automatic,0
85,camry,2006,2.50,23.73,142000,Petrol,Individual,Automatic,3
86,land cruiser,2010,35.00,92.60,78000,Diesel,Dealer,Manual,0
94,corolla altis,2008,4.00,22.78,89000,Petrol,Dealer,Automatic,0

In [52]:
h=df[(df['Fuel_Type']=='Petrol') & (df['Selling_Price']<50000) & (df['Kms_Driven']<5000)]
h1=h.shape[0]
h1

21

# 67

In [53]:
df=pd.read_csv("ipl-matches.csv")
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 576.2 KB

In [55]:
gt=df[(df["SuperOver"]=="Y") & (df["WinningTeam"]=="Gujarat Titans")].shape[0]
print(gt)

0

In [56]:
df.tail()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [57]:
rcb=df[((df["Team1"]=="Royal Challengers Bangalore") & (df["Team2"]=="Kolkata Knight Riders"))|
    ((df["Team2"]=="Royal Challengers Bangalore") & (df["Team1"]=="Kolkata Knight Riders"))
    ]
print(rcb["WinningTeam"].value_counts())

WinningTeam
Kolkata Knight Riders          16
Royal Challengers Bangalore    14
Name: count, dtype: int64

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 576.2 KB

In [59]:
tw=df[df["TossWinner"]==df["WinningTeam"]].shape[0]
tw

489

In [60]:
dl=df[(df["method"]=="D/L") & (df["WonBy"]=="Wickets")].shape[0]
dl

8

In [61]:
rrr=df[(df["TossWinner"]=="Rajasthan Royals") & (df["WinningTeam"]=="Rajasthan Royals")].shape[0]
rrr

49

In [62]:
p=df[(df["Player_of_Match"]=="V Kohli") & ((df["Team1"]=="Chennai Super Kings")|
    (df["Team2"]=="Chennai Super Kings"))].shape[0]
p

2

In [63]:
f=df[(df["City"]=="Dubai") & (df["MatchNumber"]=="Final")]
print(f[["TossWinner","Season"]])

               TossWinner Season
74  Kolkata Knight Riders   2021

In [64]:
f1=df[(df["MatchNumber"]=="Final") & ((df["Team2"]=="Kolkata Knight Riders")|
                                      (df["Team1"]=="Kolkata Knight Riders")) &
   (df["TossDecision"]=="field") & (df["TossWinner"]=="Kolkata Knight Riders")]
f1

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
492,734049,Bangalore,2014-06-01,2014,Final,Kolkata Knight Riders,Kings XI Punjab,M Chinnaswamy Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,3.0,NaN,MK Pandey,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['V Sehwag', 'M Vohra', 'GJ Bailey', 'WP Saha'...",HDPK Dharmasena,BNJ Oxenford

In [65]:
import pandas as pd

In [66]:
df=pd.read_csv("ipl-matches.csv")
df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 576.2 KB

In [68]:
r=df[(df["WinningTeam"]=="Gujarat Titans")&
      (df["SuperOver"]=="Y")]
print(r.shape[0])

0

In [69]:
r=df[(df["WinningTeam"]=="Royal Challengers Bangalore")&
    ((df["Team1"]=="Kolkata Knight Riders")|(df["Team2"]=="Kolkata Knight Riders"))]
print(r.shape[0])

14

In [70]:
r=df[((df["Team1"]=="Kolkata Knight Riders")&(df["Team2"]=="Royal Challengers Bangalore"))|
    ((df["Team2"]=="Kolkata Knight Riders")&(df["Team1"]=="Royal Challengers Bangalore"))]
print(r["WinningTeam"].value_counts())

WinningTeam
Kolkata Knight Riders          16
Royal Challengers Bangalore    14
Name: count, dtype: int64

In [71]:
r=df[df["TossWinner"]==df["WinningTeam"]]
print(r.shape[0])

489

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 576.2 KB

In [73]:
r=df[(df["WonBy"]=="Wickets")&
    (df["method"]=="D/L")]
print(r.shape[0])

8

In [74]:
r=df[(df["Player_of_Match"]=="V Kohli")&
    ((df["Team1"]=="Chennai Super Kings")|(df["Team2"]=="Chennai Super Kings"))]
print(r.shape[0])

2

In [75]:
r=df[(df["MatchNumber"]=="Final") & (df["City"]=="Dubai")]
print(r[["TossWinner","Season"]])

               TossWinner Season
74  Kolkata Knight Riders   2021

In [76]:
r=df[(df["MatchNumber"]=="Final")&
    ((df["Team1"]=="Kolkata Knight Riders")|(df["Team2"]=="Kolkata Knight Riders"))&
    (df["TossWinner"]=="Kolkata Knight Riders")&
    (df["TossDecision"]=="field")]
print(r)

          ID       City        Date Season MatchNumber                  Team1  \
74   1254117      Dubai  2021-10-15   2021       Final    Chennai Super Kings
492   734049  Bangalore  2014-06-01   2014       Final  Kolkata Knight Riders

                     Team2                                Venue  \
74   Kolkata Knight Riders  Dubai International Cricket Stadium
492        Kings XI Punjab                M Chinnaswamy Stadium

                TossWinner TossDecision SuperOver            WinningTeam  \
74   Kolkata Knight Riders        field         N    Chennai Super Kings
492  Kolkata Knight Riders        field         N  Kolkata Knight Riders

       WonBy  Margin method Player_of_Match  \
74      Runs    27.0    NaN    F du Plessis
492  Wickets     3.0    NaN       MK Pandey

                                          Team1Players  \
74   ['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...
492  ['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...

                                          Team2Players          Umpire1  \
74   ['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...      Nitin Menon
492  ['V Sehwag', 'M Vohra', 'GJ Bailey', 'WP Saha'...  HDPK Dharmasena

            Umpire2
74   RK Illingworth
492    BNJ Oxenford